[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "pyg-captum-shap"
version = "0.1.3"
authors = [
  { name="Magnus Stroemme", email="magnus.henrik@hotmail.com" },
]
description = "A robust SHAP explainer wrapper for PyTorch Geometric models."
readme = "README.md"
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
    "Topic :: Scientific/Engineering :: Chemistry"
]
dependencies = [
    "torch>=2.0.0",
    "torch_geometric>=2.0.0",
    "captum>=0.6.0"
]

[project.urls]
"Homepage" = "https://github.com/username/pyg-captum-shap"
"Bug Tracker" = "https://github.com/username/pyg-captum-shap/issues"
